### ISSUE TITLE
Improve community list filtering and columns

### ISSUE THREAD

**Issue by tristanlatr** [LesFruitsDefendus/saskatoon-ng#10]
Allow the filtering by Role in the community panel.
Allow to show the number of picks the pickers got accepted / refused.

See also: https://github.com/tiagovaz/saskatoon/issues/33

**Comment by 2ynn** [comment]
![screenshot_2021-10-23_20:52:59](https://user-images.githubusercontent.com/41802320/138575729-f95d31dc-b394-4545-b25e-aa47c5259d7e.png)

- [x] filtering by Role in the community panel.
- [x] show the number of picks the pickers got accepted
- [ ] show the number of picks the pickers got refused

**Comment by 2ynn** [comment]
- blue = upcoming harvests (either for pickleader/core or *accepted* volunteers)
- red = cancelled harvests (including for *accepted* volunteers)
- green = suceeded harvests (including for *accepted* volunteers)
- yellow = volunteer request is pending
- grey = "missed harvests" : volunteer has either cancelled or was rejected
- 
![screenshot_2021-11-09_21:35:59](https://user-images.githubusercontent.com/41802320/141039472-436fb2d6-a434-46b3-ae01-fe6633105adf.png)
