### ISSUE TITLE
Add editable HomePage model

### ISSUE THREAD

**Issue by 2ynn** [LesFruitsDefendus/saskatoon-ng#117]
To allow core-members to dynamically edit the content of the home page:
- title (Welcome)
- image (Banner)
- description (LFD about)
- volunteer instructions (rendered as |safe)
- pickleader instructions (rendered as |safe)

See also FAQ in issue #29

**Comment by khabdrick** [comment]
is this issue still available, I'll like to work on it?

**Comment by tristanlatr** [comment]
Hello @khabdrick,

Note that this issue was initially part of the internship itself, because it would probably introduce quite a big diff.

But if you feel confident you can achieve task in the contribution period, please go ahead.

**Comment by khabdrick** [comment]
Now I don't feel confident anymore. I'll pick something lighter so that it can be finished and reviewed in time.
I'm sorry for the confusion.

**Comment by 2ynn** [comment]
no worries, sorry for the django-dotenv / python-dotenv confusion, that was on our side

**Comment by tristanlatr** [comment]
@khabdrick you can review the issues marked as "easy" or "good first issue" :)

Talk to you later,

**Comment by 2ynn** [comment]
no worries @khabdrick !

**Comment by victorphoenix3** [comment]
Hi, I would like to work on this issue?

What I am thinking is that instead of hard coding the values in templates, we should introduce a model with the fields that can be edited in the admin panel and then we could render the fields dynamically. Do you think this would work? @2ynn @tristanlatr

**Comment by tristanlatr** [comment]
> we should introduce a model with the fields that can be edited in the admin panel and then we could render the fields dynamically. 

yes this is the plan :) as I mentioned above, please make sure you feel confident to complete this task within the contribution period before working in this.

Talk to you later,
