### ISSUE TITLE
Improve admin panel list displays

### ISSUE THREAD

**Issue by 2ynn** [LesFruitsDefendus/saskatoon-ng#119]
At least these two need extra list_display fields, search options, filters, etc..:
- [x] http://localhost:8000/admin/harvest/property/
- [x] http://localhost:8000/admin/member/person/

**Comment by Rufaida98** [comment]
@2ynn i cant open the linky you attached

**Comment by ojaragodwin** [comment]
> 

To open the link that @2ynn submitted, you need to have set up the application running locally on your machine already
