### ISSUE TITLE
Fix the season filter

### ISSUE THREAD

**Issue by tristanlatr** [LesFruitsDefendus/saskatoon-ng#123]
Go to https://saskatoon-dev.lesfruitsdefendus.org/harvest/ and try to select another season that 2021, you will maybe see a pop with a datetime selector (like in harvest datetime scheduling).  

The plain dropdown list also shows on top of the datetime selector.

Should not be too hard to simply remove the datetime selector. 

![Capture d’écran, le 2022-03-18 à 16 43 42](https://user-images.githubusercontent.com/19967168/159080629-9d87c320-4cac-4f69-bc16-0c18e0540801.png)

**Comment by 2ynn** [comment]
see #146
