### ISSUE TITLE
Make the register button more evident 

### ISSUE THREAD

**Issue by tristanlatr** [LesFruitsDefendus/saskatoon-ng#124]
The register button for newly created members of the [community](https://saskatoon-dev.lesfruitsdefendus.org/community/) is tiny.
I'de suggest something more obvious like "Register user" or "Reset password" if the user password's is already set.
We can keep the icon, but I feel like some text should be also present. Note that "register" text appears only on hover.

<img width="79" alt="by default 2022-03-24 at 12 37 14 PM" src="https://user-images.githubusercontent.com/19967168/159965961-4b9a002b-9984-4996-b463-43013ad264d7.png">

**Comment by yuktea** [comment]
I would like to work on this.

**Comment by victorphoenix3** [comment]
> I would like to work on this.

Hi @yuktea, I had already been working on this and didn't see your comment before submitting the PR.

**Comment by victorphoenix3** [comment]
> I would like to work on this.

Hi @yuktea, I had already been working on this and didn't see your comment before submitting the PR.
