### ISSUE TITLE
Add urls for harvests in the property detail view.

### ISSUE THREAD

**Issue by mina-andajos** [LesFruitsDefendus/saskatoon-ng#157]
I believe adding a link for each harvest in the data row would enhance the usability of `localhost/property/<pk>`

![image](https://user-images.githubusercontent.com/52796958/160881561-9d45299e-2efb-463e-8ee0-5595c6606672.png)
--------------
Similar to `localhost/harvest/`

![image](https://user-images.githubusercontent.com/52796958/160883146-c3b46f3c-325a-46d8-aefd-4f379eda6881.png)

**Comment by tristanlatr** [comment]
Hi @mina-andajos, Yes that is a good idea.
