### ISSUE TITLE
Rebuild translation files

### ISSUE THREAD

**Issue by tristanlatr** [LesFruitsDefendus/saskatoon-ng#158]
We need to update translation files with makemessages, then we'll be able to work on translations with rosetta. 

https://docs.djangoproject.com/en/4.0/ref/django-admin/#makemessages

**Comment by victorphoenix3** [comment]
Hello @tristanlatr. I'll work on this issue.

**Comment by tristanlatr** [comment]
Hi @victorphoenix3, sounds good, thanks.
