### ISSUE TITLE
Add "under development" notes for missing features

### ISSUE THREAD

**Issue by tristanlatr** [LesFruitsDefendus/saskatoon-ng#16]

**Comment by mina-andajos** [comment]
Could you please explain further? You want to look for which features?

**Comment by tristanlatr** [comment]
Hi @mina-andajos, 

The missing feature forth at would be good to have a placeholder for would the statistics page, see #115. Maybe the page can contain “raw” data with a note that statistics processing is under development.

Thanks

**Comment by mina-andajos** [comment]
I'm sorry I still don't understand.
The statistics page like already a static page with placeholder values.
You want to add a note in the title/header that it's under development maybe?
I don't get the raw data part to be exact.

**Comment by tristanlatr** [comment]
> You want to add a note in the title/header that it's under development maybe?

Yes

> I don't get the raw data part to be exact.

Forget about that, we can use the admin panel.

**Comment by mina-andajos** [comment]
Working on it right now. 👍
