### ISSUE TITLE
Wrong success_url on PropertyCreatePublicView

### ISSUE THREAD

**Issue by farhanmasud** [LesFruitsDefendus/saskatoon-ng#173]
`success_url` on `PropertyCreatePublicView` located at [saskatoon/harvest/views.py](https://github.com/LesFruitsDefendus/saskatoon-ng/blob/develop/saskatoon/harvest/views.py#L67) is set to `'thanks'` which doesn't exist. So when users enter the details and click on the Send button, they are redirected to a 404 page.

![Screenshot from 2022-04-04 02-26-13](https://user-images.githubusercontent.com/43474661/161447092-0345977f-16d9-41d9-8050-067e463d7d7a.png)

**Comment by tristanlatr** [comment]
Hi @farhanmasud,

Thanks for creating this issue,

This is a know bug and it would great to be fixed. The thank you page can be very simple, with a text and a button to come back to the main Saskatoon URL. 

Someone (@2ynn) is telling in my earphone that this page might already exist under a different name: property/thanks

**Comment by farhanmasud** [comment]
@tristanlatr thanks a lot for your feedback. I have updated the `success_url` on [this pr](https://github.com/LesFruitsDefendus/saskatoon-ng/pull/174) which points to the url that you have mentioned. I'll update the template accordingly as well.
