### ISSUE TITLE
Update favico 

### ISSUE THREAD

**Issue by tristanlatr** [LesFruitsDefendus/saskatoon-ng#175]
The icon should be: https://saskatoon-dev.lesfruitsdefendus.org/static/img/logo.png

**Comment by S-kus** [comment]
Hello @tristanlatr, I updated the required favicon.ico in the attached pull request. Could you please review it?
Thanks!

**Comment by tristanlatr** [comment]
Hello @S-kus. Thanks for your contribution. It looks very good.

**Comment by S-kus** [comment]
Looking forward to more contributions!
