### ISSUE TITLE
Clarify install 

### ISSUE THREAD

**Issue by tristanlatr** [LesFruitsDefendus/saskatoon-ng#178]
See https://github.com/LesFruitsDefendus/saskatoon-ng/commit/cbe7dd649f713ef57604a2033e76d7b748969c31#r70308824

**Comment by S-kus** [comment]
Hey @tristanlatr, I like to work on this issue. 
Could you confirm, What exactly I needed to clarify?

Like should I add earlier instructions i.e.
```
from django.core.management import utils
print(utils.get_random_secret_key())
```
and wrote to start python in terminal using `python3` or `python`

 or do I need to write an explanation line for this command:
`python -c 'from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())'`

**Comment by tristanlatr** [comment]
Hi @S-kus, Thanks for your interest.

It's really on replacing "Note: to generate a new random secret key, you can run this python script:" by "Note: to generate a new random secret key, you can run this script:" (since it's not a python script anymore, but just a sh script)

**Comment by S-kus** [comment]
Thanks, @tristanlatr for clarification, I created the pull request.
Could you please review it!
