### ISSUE TITLE
".env is not found" Error !

### ISSUE THREAD

**Issue by sreshu** [LesFruitsDefendus/saskatoon-ng#180]
File "/home/<user_name>/venv/lib/python3.8/site-packages/django/conf/__init__.py", line 170, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/reshu.singh/saskatoon-ng/saskatoon/saskatoon/settings.py", line 28, in <module>
    raise IOError('.env file not found!')
OSError: .env file not found!

**Comment by ojaragodwin** [comment]
You are supposed to create a ".env" file int root directory and copy all the contents of the "env.template" in the root directory to the ".env" file you just created as per the instructon in the INSTALL.md file line 71

![image](https://user-images.githubusercontent.com/38132692/161504333-e5012b6a-2fc0-4236-ab01-6b83e506bcf4.png)

I hope this helps @sreshu 
You will meet another error which you solve by creating and sqlite3 database and seting the path to the appropriate local path in your machine. This path  setting is done in the .env file you have created in line 15

@tristanlatr  I hope I am right here

**Comment by ojaragodwin** [comment]
You can create it at the root as show in this picture
![image](https://user-images.githubusercontent.com/38132692/161510190-9a4c5b54-7a3e-487b-bb63-ac5027638238.png)

**Comment by ojaragodwin** [comment]
And then copy the path and edit the .env file path line 15 to point to this database you have just created

**Comment by ojaragodwin** [comment]
> @ojaragodwin , SASKATOON_DB_NAME=/your/db/path/sqlite3.db, for this do i need create a new db here?

Please make sure the db is named as "db.sqlite3" not "sqlite.db"

**Comment by sreshu** [comment]
@ojaragodwin so this db.sqlite3 would be empty?

**Comment by ojaragodwin** [comment]
> @ojaragodwin so this db.sqlite3 would be empty?

Yes it would be empty, but it will be pupulated when you run migration commands in django, and also be populated when you load the data from the json files, kindly read the INSTALL.md file carefully

**Comment by tristanlatr** [comment]
Thanks @ojaragodwin  for debugging this issue.
@sreshu I hope everything is working on your end, don't hesitate to open more issues or discussions.

Closing it now :)
