### ISSUE TITLE
Do not assume all owners are Persons

### ISSUE THREAD

**Issue by 2ynn** [LesFruitsDefendus/saskatoon-ng#188]
I've assumed all property owners were `Person`s without realizing `Organization`s can also be owners (`owner` field is related to `Actor`, not `Person`)
```
./saskatoon/sitebase/templates/app/list_views/property/status.html:21:    {% if property.owner.person.about %}
./saskatoon/sitebase/templates/app/list_views/property/status.html:22:        <li><i class="fa fa-envelope"></i> {{ property.owner.person.email }}</li>
./saskatoon/sitebase/templates/app/detail_views/property/similar_row.html:23:        {% with property.owner.person as po %}
./saskatoon/sitebase/templates/app/detail_views/harvest/about.html:53:                                <h4>{{ property.owner.person.phone }}</h4>
./saskatoon/sitebase/templates/app/detail_views/harvest/about.html:60:                                <h4>{{ property.owner.person.email }}</h4>
./saskatoon/sitebase/templates/app/detail_views/harvest/about.html:64:                        {% if property.owner.person.language != 'None' %}
./saskatoon/sitebase/templates/app/detail_views/harvest/about.html:68:                                <h4>{{ property.owner.person.language }}</h4>
./saskatoon/sitebase/templates/app/detail_views/harvest/about.html:73:                        {% if property.owner.person.comments %}
./saskatoon/sitebase/templates/app/detail_views/harvest/about.html:77:                                <h4>{{ property.owner.person.comments }}</h4>
./saskatoon/harvest/admin.py:99:        'owner__person__family_name',
./saskatoon/harvest/admin.py:100:        'owner__person__auth_user__email',
./saskatoon/harvest/utils.py:29:            query |= Q(owner__person__auth_user__email=email)
./saskatoon/harvest/autocomplete.py:26:            q2 = Q(owner__person__first_name__icontains=self.q)
./saskatoon/harvest/autocomplete.py:27:            q3 = Q(owner__person__family_name__icontains=self.q)
```
There may be more. See `app/list_views/equipment/data_row.html` for an example where a distinction between the two types of actors is made.

I suggest starting by adding "friendly" `@property` to the `Actor` model:
- `is_person`: returns True if the actor is a person (i.e. `hasattr(actor, 'person')`)
- `is_organization`: returns True if the actor is an organization (i.e. `hasattr(actor, 'organization')`)

Then to the `Property` model:
- `get_owner_name()`: person's name or organization's contact_person's name depending on `owner.is_person`/`owner.is_organization`
- `get_owner_email()`: person's email or organization's contact_person's email depending on `owner.is_person`/`owner.is_organization`
- `get_owner_phone()`: person's phone or organization's phone depending on actor type

Also I see this block commented out in `harvest.models`, I think it had a similar intent.
```
    # def get_owner_subclass(self):
    #     from member.models import Person, Organization
    #     try:
    #         return Person(self.owner)
    #     except Person.DoesNotExist:
    #         return Organization(self.owner)
```

**Comment by 2ynn** [comment]
TODO in http://localhost:8000/admin/harvest/property/ t
- [ ] add filter to differentiate properties attached to Persons from the ones associated to organizations
- [ ] show contact_name + contact_phone + contact_email in list_display (see `@properties` above)
- [ ] add pk
- [ ] skim through list_display titles for better readability

**Comment by ojaragodwin** [comment]
I would like to work on this issue,

**Comment by victorphoenix3** [comment]
@2ynn Since, I am already familiar with this part of the codebase, can I work on the above tasks?

**Comment by ojaragodwin** [comment]
Its okay @victorphoenix3 , i will work  on filters

**Comment by 2ynn** [comment]
thanks @victorphoenix3 @ojaragodwin. I've just created a branch for this Issue: https://github.com/LesFruitsDefendus/saskatoon-ng/tree/Fix-188-Not_all_owners_are_persons
Please target your pull requests to this branch, I'll try and help when i can

**Comment by ojaragodwin** [comment]
Hello @victorphoenix3 , have you figured out how to workout the harvest/models part

**Comment by ojaragodwin** [comment]
if you are having any issues kindly let me know how i can help, i am done working on the other filters, though some of them require the harvest/model  and member/model you are going to work on to be done first

**Comment by 2ynn** [comment]
thank you so much @victorphoenix3 for your PR, I'll merge it shortly and build off it

**Comment by 2ynn** [comment]
@ojaragodwin do you still want to submit a pull request to the `Fix-188-Not_all_owners_are_persons` branch for admin filters?

**Comment by ojaragodwin** [comment]
yes @2ynn, i will submit a pull request for that  since we had divided the work i was waiting for @victorphoenix3  to do the models and then i work on the filters i am already working on them, i will submit it

**Comment by 2ynn** [comment]
@victorphoenix3 @ojaragodwin  I just pushed changes to `Fix-188-Not_all_owners_are_persons`
- changed `name` and `email` for model properties in Actor model
- I think keeping functions with names  like `get_something()` without the property tag.

Let me know if you have any issues with the changes. Thanks!

**Comment by 2ynn** [comment]
@ojaragodwin I've pushed a PropertyOwnerTypeAdmin filter. I'm sorry but I need to move on with this issue as I need to clean the production database asap
