### ISSUE TITLE
Correct login page

### ISSUE THREAD

**Issue by khabdrick** [LesFruitsDefendus/saskatoon-ng#206]
![2022-04-08_14-25](https://user-images.githubusercontent.com/57852546/162445337-ff239b5a-0bca-413d-aff7-dacd5920c7c3.png)

The login page has a placeholder of username instead of email. It caused a bit of confusion at first.

**Comment by khabdrick** [comment]
I'll like to work on this issue

**Comment by tristanlatr** [comment]
Thanks!
