### ISSUE TITLE
cannot import name 'load_dotenv' from 'dotenv'

### ISSUE THREAD

**Issue by Codde24** [LesFruitsDefendus/saskatoon-ng#210]
On running my test i get the above import error. I have tried installing the python-dotenv package and uninstalled the dotenv package, but still getting the same error.

**Comment by farhanmasud** [comment]
@Codde24 I think you'll need [django-dotenv](https://github.com/jpadilla/django-dotenv) for this as the `develop` (as well as `master`) branch uses this package.

Please refer to [#137](https://github.com/LesFruitsDefendus/saskatoon-ng/pull/137).

**Comment by farhanmasud** [comment]
@Codde24 on a clean new install, `$ pip install .` inside your virtual environment (make sure you are not using any older virtual environment that you have created) should automatically install all the dependencies. [Ref.](https://github.com/LesFruitsDefendus/saskatoon-ng/blob/develop/INSTALL.md#requirements)
