### ISSUE TITLE
Include a back home link in error pages

### ISSUE THREAD

**Issue by tristanlatr** [LesFruitsDefendus/saskatoon-ng#211]
I ran into this issue trying to login (this instance (saskatoon.lesfruitsdefendus.org) is now using the code in the `prod` branch), probably due because of invalid cache in the browser (or maybe not), this is not really important, because the login was successful anyway. 

But it would be good to have a button to come back to the home page included in the default template of the error pages.

<img width="526" alt="by default 2022-04-08 at 8 13 03 PM" src="https://user-images.githubusercontent.com/19967168/162548527-85c71909-f03e-4727-aab1-32434969fd56.png">

**Comment by victorphoenix3** [comment]
@tristanlatr Hi, should we create our own error page and add a back button to it? I can't find a way to edit the default error page in django.
We could point to our custom error page when DEBUG is set to False, in other cases we could point to the default django error page. What do you think?

**Comment by tristanlatr** [comment]
Hi @victorphoenix3,

Yes that could work too, if we find a manner to keep the error code information.

Thanks for looking into that
