### ISSUE TITLE
Have the tree names aside icons in the property list

### ISSUE THREAD

**Issue by tristanlatr** [LesFruitsDefendus/saskatoon-ng#212]
Since not all trees have icons for now, and even if they would, if think it would be good to have the tree names, like in the harvest view.

<img width="755" alt="by default 2022-04-08 at 8 22 46 PM" src="https://user-images.githubusercontent.com/19967168/162548945-5b87f31d-f63d-4cd4-9d65-427e85c0f481.png">

**Comment by mina-andajos** [comment]
I will work on it 👍
