### ISSUE TITLE
Fix register owner based on pending property

### ISSUE THREAD

**Issue by 2ynn** [LesFruitsDefendus/saskatoon-ng#221]
in `/person/create/?pid=<pending_property_id>/`

https://github.com/LesFruitsDefendus/saskatoon-ng/blob/f032e5a9a5b717df43acc4f3ef8e1daed5350016/saskatoon/member/views.py#L26

now breaks because phone is no longer a string but a PhoneField: `'PhoneNumber' object has no attribute 'replace'`

To be tested:
```
 'phone': p.pending_contact_phone
```

Note: this functionality assumes the owner is a Person, not an Organization. We should maybe consider adding a `is_organization` checkbox to the public property form

**Comment by farhanmasud** [comment]
@2ynn I'd like to work on this if you didn't already spend time working on a fix for this (asking as if you've self assigned this). As I worked with the codebase for making the changes with the `PhoneField` I think I can find a fix for this.

**Comment by 2ynn** [comment]
@farhanmasud ok yes please go ahead, I quickly tested and `'phone': p.pending_contact_phone.` will work just fine. You can add the change along with your other PR for issue #222 if you want.

**Comment by farhanmasud** [comment]
> Note: this functionality assumes the owner is a Person, not an Organization. We should maybe consider adding a `is_organization` checkbox to the public property form

@2ynn what will be the backend logic for this field? I mean, where we should store the value that user inputs here? Does a new model field need to be created? Or should this value programmatically alter value for some other field (e.g. save a new instance of `Organization` model)?

There is already a property is being developed with the same name `is_organization` as per [#188](https://github.com/LesFruitsDefendus/saskatoon-ng/issues/188) that you have suggested. Creating a new model field with the same name will conflict the property name when they are merged.

**Comment by 2ynn** [comment]
@farhanmasud let's leave that aside for now. There are not a lot of organizations that own trees (most are beneficiary organizations) and they can be contacted separately by core members (without using the public form). So it's okay to assume all pending properties are for `Person` owners for now.
That being said I would like to add a safeguard in `PersonCreateForm`: https://github.com/LesFruitsDefendus/saskatoon-ng/blob/ebc6660b5c996463245472eb294161df38cc33bd/saskatoon/member/forms.py#L56
```
        pid = self.cleaned_data['pending_property_id']
        if pid:
            try:
                pending_property = Property.objects.get(id=pid)
                pending_property.owner = instance
                pending_property.save()
            except Exception as e: print(e)
```
I feel like we should not only check if there is a `pid` that was passed to the form but also if the `Property Owner` check box is ticked in `Roles`.

**Comment by tristanlatr** [comment]
At the current stage of things right, we send this form to our mailing list, not organizations. I think it’s ok to simply add a note saying that this form is for persons with a tree on their property and community organizations should contact us directly.

**Comment by farhanmasud** [comment]
@2ynn @tristanlatr I have updated accordingly on [this PR](https://github.com/LesFruitsDefendus/saskatoon-ng/pull/224). Please let me know if the updates are correct. Also, I haven't squashed the commits since the 4 commits deal with different parts / functionalities of the codebase.

**Comment by 2ynn** [comment]
thanks @farhanmasud works great
