### ISSUE TITLE
Fix PersonCreateForm validation

### ISSUE THREAD

**Issue by 2ynn** [LesFruitsDefendus/saskatoon-ng#222]
`forms.ValidationError` does not show in `PersonCreateForm` when trying to create a new user with duplicate email address

To reproduce, 
1. create a new user using an email address that is already taken in the database:
http://localhost:8000/person/create/
2. form does not save but no error message is prompted
3. change the email for a new email address. the form saves properly

**Comment by farhanmasud** [comment]
I'm working on the `PublicPropertyForm` validation on [#116](https://github.com/LesFruitsDefendus/saskatoon-ng/issues/116), I'd like to work on this issue since both are related to form validations.

**Comment by farhanmasud** [comment]
I think I have found the bug. I'm making a PR shortly.
