### ISSUE TITLE
Have a link to the property record from the harvest record

### ISSUE THREAD

**Issue by tristanlatr** [LesFruitsDefendus/saskatoon-ng#242]
![by default 2022-04-14 at 10 51 30 AM](https://user-images.githubusercontent.com/19967168/163416136-0d309f40-1043-43e6-bad8-7157fe25acdd.png)

The street address should be a link, that would increase usability.

**Comment by ejangphoebe00** [comment]
@tristanlatr can i be assigned this issue?.

**Comment by tristanlatr** [comment]
Hello @ejangphoebe00, sorry but I think this issue has already been worked on.

**Comment by ejangphoebe00** [comment]
could you assign me a new issue?.. i have looked through the issue tracker and all i  have seen have been solved
