### ISSUE TITLE
Having a proper logging system

### ISSUE THREAD

**Issue by tristanlatr** [LesFruitsDefendus/saskatoon-ng#265]
We can use the standard `logging` module.

**Comment by victorphoenix3** [comment]
Hi, I am familiar with `logging` module. I'd like to work on this issue.

**Comment by 2ynn** [comment]
I suggest setting up:
- console logging (DEBUG level)
- 1 file (WARNING level) for django warnings/errors
- at least 1 file (INFO level) using TimedRotatingFileHandler, e.g. for keeping track of emails sent or background tasks

https://docs.djangoproject.com/en/4.0/topics/logging/
