### ISSUE TITLE
Property filters should match status name

### ISSUE THREAD

**Issue by tristanlatr** [LesFruitsDefendus/saskatoon-ng#266]
Currently it show "Yes", "No" and "Unknown". Where we should read, depending on the status field, each statuses names + "All". 

So for instance for the authorization status: "Authorized", "Not Yet authorized", "Not authorized" and "All".

**Comment by 2ynn** [comment]
@tristanlatr actually `authorized` is a boolean field so the current filter makes sense.
Where did you see the "Not authorized yet" ?

**Comment by tristanlatr** [comment]
Arf.. maybe it’s a Boolean optional field, so None is allowed ?
Because I’m ready this in the guides: https://lesfruitsdefendus.readthedocs.io/en/latest/pre-pick-guide/annexes/D-using-the-property-list.html#authorization-status
