### ISSUE TITLE
Create a public FAQ about calendar usage 

### ISSUE THREAD

**Issue by tristanlatr** [LesFruitsDefendus/saskatoon-ng#29]
From https://github.com/tiagovaz/saskatoon/issues/133

Create a FAQ on how the calendar works--> "How to Sign Up for a Pick".

**Comment by tristanlatr** [comment]
Here's the current documentation about calendar usage, is it enough?

![Capture d’écran, le 2022-03-18 à 16 37 44](https://user-images.githubusercontent.com/19967168/159079963-8973b2b4-6f8f-4de5-ab83-93ca42745995.png)

**Comment by mina-andajos** [comment]
What kinds of questions have the volunteers asked before on the old saskatoon site regarding applying to harvests? There are some boolean fields like owner wants to join, stuff like that maybe? I'll check if there's anything that needs to be de-mystified.

**Comment by richarddushime** [comment]
Greetings to @mina-andajos 
As i was going through the process for harvest so that i can work on this  i realized that  there is some fields that are missing in the harvests status there is no open and full or according to documentation   for someone to participate  the status has to be open 
i could  first add that then i proceed to improve the documentation if you accept 
Thank you

**Comment by tristanlatr** [comment]
Hello @richarddushime and @mina-andajos,

Sorry @mina-andajos, your message fall thought the cracks here.

The full documentation can be found in the guides: https://github.com/LesFruitsDefendus/guides although I agree there is no description of each specific harvest status.

@richarddushime, I believe the statuses in the calendar are simplified from the list of real statuses a harvest can have: https://github.com/LesFruitsDefendus/saskatoon-ng/blob/624d35c43967ea2ebd205b6a0d836fadfe52b6bc/saskatoon/harvest/models.py#L12

I think this issue can be closed for now, but we're missing some documentation for the pickleaders for sure.

I'll create another issue for that.

**Comment by tristanlatr** [comment]
I've found the docs in the pre-pick guide:

![by default 2022-04-08 at 12 42 03 AM](https://user-images.githubusercontent.com/19967168/162364938-8c016b3d-a5f5-4009-a20c-6c296e63e247.png)

So we're good for the documentation.
