### ISSUE TITLE
Fix the 'buckets' links to the harvests from the property list

### ISSUE THREAD

**Issue by tristanlatr** [LesFruitsDefendus/saskatoon-ng#293]
Previous harvests link doesn’t work under Properties -> Click on the buckets -> Error message
![by default 2022-05-19 at 6 06 12 PM](https://user-images.githubusercontent.com/19967168/169412391-70bc1122-6a5b-413d-a2b2-f60c3efe15c5.png)

**Comment by 2ynn** [comment]
Fixed by #276
