### ISSUE TITLE
Add legend with more info to the Calendar

### ISSUE THREAD

**Issue by tristanlatr** [LesFruitsDefendus/saskatoon-ng#30]
From: https://github.com/tiagovaz/saskatoon/issues/135

Add a permanent legend on the calendar for the colour coding of picks.
The legend would make it easier for volunteers to find out if a pick needs volunteers or is full.

**Comment by 2ynn** [comment]
![screenshot_2021-07-20_16:12:36](https://user-images.githubusercontent.com/41802320/126389652-9bf9d183-31ff-421d-8036-6ff90a49e92f.png)
