### ISSUE TITLE
Kudos messages for pickeaders when harvest status is set to "Succeeded"

### ISSUE THREAD

**Issue by tristanlatr** [LesFruitsDefendus/saskatoon-ng#32]
From: https://github.com/tiagovaz/saskatoon/issues/146

Ideas for text (this will need to bilingual):

“You’ve just led your "nth" fruit harvest this season! Thank you for supporting your community!”

May be in a green box somewhere, but not a pop-up.

**Comment by mina-andajos** [comment]
Can I work on this one?

**Comment by mina-andajos** [comment]
I'm checking the `harvest/property_thanks.html` template. I believe replicating it for the harvest creation would be good?

**Comment by mina-andajos** [comment]
I'm checking the message on the `harvest/property_thanks.html` template. I believe adding something similar when a Harvest's status is set to "Success" would be good?
![image](https://user-images.githubusercontent.com/52796958/160314022-0dad94f2-0ade-4697-a7c4-cf11ef746067.png)

**Comment by tristanlatr** [comment]
Yes go ahead. Thanks.

**Comment by mina-andajos** [comment]
Progress so far:
![image](https://user-images.githubusercontent.com/52796958/160320548-5323b7b6-0418-4abf-bf55-7c19fecd2748.png)

I should add the harvest name instead of 'nth' right? or the fruit type name?

**Comment by mina-andajos** [comment]
I tried using the model's `property.publishable_location` attribute:

![image](https://user-images.githubusercontent.com/52796958/160322714-45493c49-1004-42b2-adc4-d92010638902.png)

I think it looks cleaner than using the `property` attribute like the string representation of the Harvest model for example.

**Comment by tristanlatr** [comment]
Thanks! Looks good but I think I meant 'nth'  to be the number of picks the pickleader accomplished in the season, eg 1st, 2nd, 3rd, 4th, 6th, 7th, 8th, etc…

**Comment by mina-andajos** [comment]
ok, will apply that.
Do I have to run the tox test locally for this change?
I'm facing a timeout error with it that I'm trying to fix

**Comment by tristanlatr** [comment]
> Do I have to run the tox test locally for this change?

would be good that the tests passes, and if they don’t, why.
