### ISSUE TITLE
Display fruits icons 🍎🍊🍇🍒🍏

### ISSUE THREAD

**Issue by tristanlatr** [LesFruitsDefendus/saskatoon-ng#33]
From: https://github.com/tiagovaz/saskatoon/issues/115
https://github.com/tiagovaz/saskatoon/issues/148
https://github.com/tiagovaz/saskatoon/issues/136

**Comment by mina-andajos** [comment]
Would adding an `icon` field to the `TreeType` model be good?
Maybe add an optional tree icon field in the form when creating a property/harvest.
and then when we display the treetype elsewhere like on calendar
we either use just the icon or the name with the icon.

**Comment by mina-andajos** [comment]
Or maybe something like this in the views without changing the model:
```python
def get_treetype_icon(treetype:TreeType):
    treetype_icons={
        "Apple_Red":"🍎",
        "Orange":"🍊",
        "Grapes":"🍇",
        "Cherry":"🍒",
        "Apple_Green":"🍏",
    }

    return treetype_icons[treetype.name]
```

**Comment by tristanlatr** [comment]
> we either use just the icon or the name with the icon

I think the goal is to have the fruits icons aside the fruits type as text (when we have the space - like in harvest page) and have only fruit icon when we're reviewing the harvest list for instance or the history of harvest for this property.

Honestly I'm not quite sure tof the best manner to implement it. Having a mapping like that sounds like a resonable idea.

**Comment by mina-andajos** [comment]
I am working on the issue right now.

**Comment by mina-andajos** [comment]
Is it better to use `object.name` or `object.fruit.name`? @tristanlatr 

```python
class TreeType(models.Model):
    name = models.CharField(
        verbose_name=_("Name"),
        max_length=20,
        default=''
    )
    ...
    fruit_name = models.CharField(
        verbose_name=_("Fruit name"),
        max_length=20
    )
```

**Comment by mina-andajos** [comment]
nvm i looked at the templates and figured it out. it's using `tree.name`
