### ISSUE TITLE
recipient-select in Fruit Distribution form does not return Actors 

### ISSUE THREAD

**Issue by 2ynn** [LesFruitsDefendus/saskatoon-ng#331]
**Bug report**

recipient field in HarvestYield model is an actor

In `harvest/api.py` the pickers array contains AuthUser (pick_leader) + Persons (pickers). This need to be fixed, i suggest we pass:
picker = [harvest.pick_leader.person] + [...] instead so they are all persons.

in `templates/app/detail_views/harvest/distribution/recipient_select.html` we should pass the actor pk.
- Owner: it is an actor, {{ property.owner.pk }} OK
- Pickers  it should be {{ p.pk }}, provided we only pass Persons
- Organizations are actors: {{o.pk}} OK

This is a quickfix for now (my bad on getting mixed up with Actor/Person/AuthUser, it's was a bit confusing at first tbh).

Long term though we should pass the form to the view from harvest/forms.py properly (to figure out how to integrate using REST exclusively, @mina-andajos I believe it should be a bit easier to add additional context for a detail view compared to the new button issue you were encountering with the list view)

## Related URLs:
`harvest-yield-create`

**Comment by mina-andajos** [comment]
> **Bug report**
> 
> recipient field in HarvestYield model is an actor
> 
> In `harvest/api.py` the pickers array contains AuthUser (pick_leader) + Persons (pickers). This need to be fixed, i suggest we pass: picker = [harvest.pick_leader.person] + [...] instead so they are all persons.
> 
> in `templates/app/detail_views/harvest/distribution/recipient_select.html` we should pass the actor pk.
> 
> * Owner: it is an actor, {{ property.owner.pk }} OK
> * Pickers  it should be {{ p.pk }}, provided we only pass Persons
> * Organizations are actors: {{o.pk}} OK
> 
> This is a quickfix for now (my bad on getting mixed up with Actor/Person/AuthUser, it's was a bit confusing at first tbh).
> 
> Long term though we should pass the form to the view from harvest/forms.py properly (to figure out how to integrate using REST exclusively, @mina-andajos I believe it should be a bit easier to add additional context for a detail view compared to the new button issue you were encountering with the list view)
> 
> ## Related URLs:
> `harvest-yield-create`

@2ynn If I understood you correctly, the forms should be passed to the harvest detail view context right?

**Comment by 2ynn** [comment]
@mina-andajos  yea sorry for the confusion. For the "inlline" create/delete fruit distribution (in harvest detail view) I have not actually passed a proper form to the context, only a list of potential recipients. 
We could start by simply passing these recipients along with the serialized data and call the `harvest_yield_create/delete` views from the template as we do now. No need to pass an actual form I guess...

Since we're using REST  though we should eventually create proper CRUD routes to create/edit/delete a fruit distributions, but I don't think it's a priority for now
