### ISSUE TITLE
Notify tree owner once "pending" status is removed

### ISSUE THREAD

**Issue by tristanlatr** [LesFruitsDefendus/saskatoon-ng#34]
Send automatic email to tree owner to indicate that their tree subscription was reviewed and completed.
From https://github.com/tiagovaz/saskatoon/issues/192

**Comment by 2ynn** [comment]
Related to Issue #71

**Comment by victorphoenix3** [comment]
Hi @tristanlatr, May I work on this?

**Comment by tristanlatr** [comment]
Hi @victorphoenix3, 

yes go ahead, 

Talk to you later,
