### ISSUE TITLE
Make rosetta UI accessible to core members as well (not just admins)

### ISSUE THREAD

**Issue by tristanlatr** [LesFruitsDefendus/saskatoon-ng#341]
https://github.com/LesFruitsDefendus/saskatoon-ng/blob/2e04208a41a424fbfe723a970481c6b72b423b53/saskatoon/saskatoon/urls.py#L15

The "Manage Translations" button appear but it seems that core members can't access the page. 

@mina-andajos could you look into this issue ?

**Comment by mina-andajos** [comment]
> https://github.com/LesFruitsDefendus/saskatoon-ng/blob/2e04208a41a424fbfe723a970481c6b72b423b53/saskatoon/saskatoon/urls.py#L15
> 
> The "Manage Translations" button appear but it seems that core members can't access the page. 
> 
> @mina-andajos could you look into this issue ?

@tristanlatr sure!
i should base it off of master correct?

**Comment by mina-andajos** [comment]
@tristanlatr 
accessing the site as core user only
not staff/superuser/admin
![image](https://user-images.githubusercontent.com/52796958/180214031-23a069f2-73a8-4896-8a22-bd3168f725eb.png)
i don't see the button.

I also don't get access to the rosetta page
![image](https://user-images.githubusercontent.com/52796958/180214183-2b5bb7e1-c98b-452e-9fd2-ca330176e7ee.png)

----------------------
I should give access to all core members then correct?

**Comment by mina-andajos** [comment]
I noticed that core members can add persons, is this an intended behavior?
I don't have access to the rest of the links though as a core member

![image](https://user-images.githubusercontent.com/52796958/180216152-90992bb4-f99a-47eb-9ef0-b449f77abd92.png)

**Comment by mina-andajos** [comment]
> Yes, core members should be able to edit translations. But we might have to be staff as well, which is OK.
> 
> Anyway, translations can't be saved on the production server, they are read only. They must be updated thought git.

yeah just checked the rosetta docs, i believe the server should be able to auto-reload to apply the new changes?
You don't want to push to git from the server right?
![image](https://user-images.githubusercontent.com/52796958/180644716-58f07873-5cd4-42b0-b535-ef3093a47d7b.png)
