### ISSUE TITLE
Automatically adjust season filter value in menu links

### ISSUE THREAD

**Issue by 2ynn** [LesFruitsDefendus/saskatoon-ng#355]
## Current Behavior:

links to harvest list view in `app/base/menu.html` contain a hardcoded value for the season filter:
```
 <a href="{% url 'harvest-list' %}?season=2022">{% translate "Harvests" %} </a>
```

## Expected Behavior:

Automatically select the last season (i.e. current year). 
A template tag would probably be the best way to achieve this.

## Related URLs:
https://saskatoon.lesfruitsdefendus.org/harvest/?season=2023

**Comment by denisrhz** [comment]
@2ynn Hello! Let me solve this problem.

**Comment by 2ynn** [comment]
> @2ynn Hello! Let me solve this problem.

Hi @denisrhz, ok, please target the master branch for this issue.
