### ISSUE TITLE
Adjust Beneficiary organizations fields list with what has been asked in real life

### ISSUE THREAD

**Issue by tristanlatr** [LesFruitsDefendus/saskatoon-ng#36]
Fields: 

- Organization
- Adresse électronique
- Address
- Phone number, (+ contact name, if there is one )
- Contact person (and role/title)
- Other contact persons and/or phone number and/or email address
- Neighbourhood
- Notes & comments

From: https://github.com/tiagovaz/saskatoon/issues/162

**Comment by 2ynn** [comment]
Here is what the list view looks like now:
![screenshot_2021-09-11_00:04:52](https://user-images.githubusercontent.com/41802320/132935713-48ee48cf-1cce-4b1d-a9f8-753e8c22906c.png)

**Comment by tristanlatr** [comment]
So great ! Thanks a lot @2ynn

**Comment by tristanlatr** [comment]
This issue can be closed, right @2ynn ?

thanks
