### ISSUE TITLE
Property comments should allow more characters

### ISSUE THREAD

**Issue by tristanlatr** [LesFruitsDefendus/saskatoon-ng#361]
## Type of Issue: Feature request

Property comments are capped at 255 characters, it should allow more text...

**Comment by 2ynn** [comment]
I think PR #385 may have fixed this issue (changed CharField for QuillField)  @oxgr can you please check where it's at?

**Comment by oxgr** [comment]
just tested and max characters is definitely 1000 like it was set in `Harvest.about` so i'll say this is is fixed
