### ISSUE TITLE
Send automatic emails for non-selected pickers

### ISSUE THREAD

**Issue by tristanlatr** [LesFruitsDefendus/saskatoon-ng#37]
From: https://github.com/tiagovaz/saskatoon/issues/179

**Comment by yokwejuste** [comment]
Can I be asigned to this issue?

**Comment by tristanlatr** [comment]
Yes, go ahead. 

Talk to you later

**Comment by yokwejuste** [comment]
I'm an outreachy applicant and from what I learned recently, I somehow need to have the issue assigned before my work can be registered.

**Comment by tristanlatr** [comment]
> I'm an outreachy applicant and from what I learned recently, I somehow need to have the issue assigned before my work can be registered.

Not sure to understand what you are talking about exactly, I assume your talking about github assignments... We don't really use those. And this did not stop participants from contributing.  I think that knowing that you're working on this issue is probably enough to prevent other participants to work on this issue as well. 

 For the short term, you can consider that this issue is yours.

Talk to you later.

**Comment by victorphoenix3** [comment]
@yokwejuste are you working on this? If not, I would like to submit a PR for this since I have already worked with the email notifications codebase.
