### ISSUE TITLE
Organization (beneficiary and/or equipment point) list and detail pages

### ISSUE THREAD

**Issue by oxgr** [LesFruitsDefendus/saskatoon-ng#415]
## Type of Issue: **Feature request**

Beneficiaries should have their own details page to see more information on a particular organisation.

This will especially be beneficial in the future to view more details on equipment available from an organisation.

## Expected Behavior:

- Beneficiaries listed in the Beneficiary tab should have clickable links to a details page, like in Harvest and Community tabs.

## Current Behavior:

- only a list
- long & unreadable description column (could be removed with a dedicated details page)

## Related URLs:

e.g. `https://saskatoon.lesfruitsdefendus.org/beneficiary/`

**Comment by 2ynn** [comment]
- the `Beneficiary Tab` should list all organizations but the `is_beneficiary` filter should be set to True by default
- The `Equipment` tab should be replaced by a `Equipment Point` tab
- This means we will no longer list equipments that are shared by property owners. Let's make sure equipments available on the property are clearly displayed on the property page instead *as well* as any harvest detail page associated with this property. Let's ignore the `shared` property for now
- the `Equipment Point` Tab should list all organizations but the `is_equipment_point` filter should be set to True by default
- tables can have similar content on both tabs (e.g. short_description, beneficiary_description, equipment_description pop-ups

**Comment by 2ynn** [comment]
Detail page:

The Organization detail page should contain:
- contact information
- beneficiary information (if applicable)
- equipments available (if applicable) + equipment_description

Adding a `+ New Equipment` button and a `AddEquipment` form  is a nice to have, not a priority. Imo we can deal with it at later point. For now the `Organization` admin page can be used. I don't think equipment lists will change much throught the season and I expect only a few core members will be in charge of updating this information.

Eventually we will want to add a list of harvests  that have reserved this equipment point (or some calendar view?). This is good to keep in mind for layout purposes but this is out of scope for this Issue

**Comment by oxgr** [comment]
hitting a crossroads in #416

since beneficiaries and equipment points both will use the same `Organization` details page, create/update views, and possibly list pages, should we take the opportunity to rename some things that conflate Organization and Beneficiary? might save some headache in the future.

e.g.
https://github.com/LesFruitsDefendus/saskatoon-ng/blob/3308f376fa89b210b1be4ba02264f411967d0568/saskatoon/member/urls.py#L11

**Comment by 2ynn** [comment]
@oxgr I would say let's not change the actual routes but feel free to change the name `benficiary-create` -> `organization-create` for more clarity

**Comment by 2ynn** [comment]
> Doing the renaming above might make it simpler to use the same viewset for the two, reducing complexity.

I agree we should not duplicate the viewset and reuse the same for both list pages. Subclassing is fine though.

> in the same vein, would there be much of a difference in Beneficiaries and Equipment point list pages other than an initial filter? 

Some differences I  see:
- minor: we could show  only the `beneficiary_description` as pop-up in the beneficiary list page and simply have a checkmark for `has_equipment` column. Conversely show only the `equipment_description` as pop-up in the equipment point list page and simply have a checkmark for `is_beneficiary` column.
- more importantly the available filters will differ, e.g. (date_range filter for available equipment_points)
