### ISSUE TITLE
Add language support to new template

### ISSUE THREAD

**Issue by tiagovaz** [LesFruitsDefendus/saskatoon-ng#52]
It seems all the l10n core setup is already there, but we need to add it to the new template.

**Comment by tristanlatr** [comment]
Hi, not sure this has anything to do with translation, but it seems that some of the translations are working some others are not. 

The covid warning banner is translated, but not the tab titles for instance.

**Comment by tiagovaz** [comment]
Hi, yes, we need to translate lots of strings both in templates and internally. It can be done by someone from the collective, no tech skill required. I'll ask tassia to update the instructions.

**Comment by tiagovaz** [comment]
Lots of translation is still missing, but the l10n structure is well integrated to the new template.
