### ISSUE TITLE
Add active filters to views

### ISSUE THREAD

**Issue by tassia** [LesFruitsDefendus/saskatoon-ng#54]
After filtering entries, we want to see the active filters right away.

**Comment by tristanlatr** [comment]
Yes, and, ideally the filters should display on the side on screens that are large enough, like in the older version.

**Comment by 2ynn** [comment]
Still a bit clunky
![screenshot_2021-08-09_14:24:04](https://user-images.githubusercontent.com/41802320/128755218-bbdb1866-17e9-4ccf-90ba-dfd2344119fd.png)
![screenshot_2021-08-09_14:24:31](https://user-images.githubusercontent.com/41802320/128755219-babbbe6f-5c56-4227-b88e-feb8049fff4d.png)
