### ISSUE TITLE
Add a fixture for initial deployment / tests

### ISSUE THREAD

**Issue by tiagovaz** [LesFruitsDefendus/saskatoon-ng#59]

**Comment by tristanlatr** [comment]
I've created something for the testing, I don't know if you would call that a "fixture".
[createtestsuperuser.py](https://github.com/LesFruitsDefendus/saskatoon-ng/blob/setup-tests/saskatoon/tests/createtestsuperuser.py) and [runtests.sh](https://github.com/LesFruitsDefendus/saskatoon-ng/blob/setup-tests/saskatoon/tests/runtests.sh)

**Comment by tiagovaz** [comment]
This is nice to have, but by fixture I meant a json dump of a populated database for testing as described here: https://docs.djangoproject.com/en/3.2/howto/initial-data/

**Comment by qusvv** [comment]
So far the saskatoon.json fixture that I have created is a *minimal* database containing:
- 1 auth.user (superuser)
- 1 organization (fruits défendus)
- 1 fake person w/ 1 property
- 1 harvest w/ 3 harvest yields
- 1 equipment
- neighborhoods
- tree types
- equipment types

Let's discuss what we would like for a *testing* saskatoon-test.json fixture

**Comment by tiagovaz** [comment]
Done!
