### ISSUE TITLE
Add a popover or something similar to Calendar events

### ISSUE THREAD

**Issue by tiagovaz** [LesFruitsDefendus/saskatoon-ng#64]
Instead of using a direct link to the RFP form, first open a popover (on click, not on hover) with basic information about the harvest. If the harvest is still accepting pickers, then offer the user a link to the request form.

**Comment by tiagovaz** [comment]
The calendar is the public view for pickers willing to join a harvest. Therefore, the harvest info should be as clear as possible. We need to improve how it looks in the calendar view, but also on the list view.

**Comment by 2ynn** [comment]
Hey do you mind if I take a look at this? I think it's pretty important as for now even successful harvests link to a RFP form

**Comment by tiagovaz** [comment]
yes yes please, that would be great. I tried to add something with more info about the harvest but failed on the js side. Thanks.

**Comment by 2ynn** [comment]
Layout could definitely be improved but modal popups are now functional: https://saskatoon-dev.lesfruitsdefendus.org/calendar

- only `Date-scheduled` events link to the RFP form
- when logged in, cancelled events also show on the calendar and an additional  `Harvest Detail` button is available in the pop-up
