### ISSUE TITLE
Removing and avoiding the start imports

### ISSUE THREAD

**Issue by tristanlatr** [LesFruitsDefendus/saskatoon-ng#68]
Hi @tiagovaz ,

I'm trying to get rid of the things like:

```python
from harvest.forms import *
```

Could we please not use start imports anymore in the new code and thinking about refactoring such that we can trace each python identifier back to it's source. It will also help the static checkers to report more informative errors. 

Thanks :)

**Comment by tiagovaz** [comment]
Sure, go ahead. I'm still with tons of blocking issues and this is not my priority now. I'm using Pycharm free edition and it's a big mess with imports.

**Comment by yokwejuste** [comment]
Can i work this out and make the code clean?

**Comment by tristanlatr** [comment]
We don't want to introduce big diffs right now, so major code cleaning should be kept for later (after we have merged #114).
