### ISSUE TITLE
Logoff should redirect to the default login page, not the djando admin login page 

### ISSUE THREAD

**Issue by tristanlatr** [LesFruitsDefendus/saskatoon-ng#72]
Currently logoff redirects me to a django admin page, maybe it's because I'm an admin ? In any case it should be changed I think. 

Also another bug with redirection is that if we load the login form without the `next` parameters, it goes automatically to `/accounts/profile`, which is a 404 not found.

**Comment by 2ynn** [comment]
```
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'
```
added to settings.py:
