### ISSUE TITLE
Show the user name or email of the person connected

### ISSUE THREAD

**Issue by tristanlatr** [LesFruitsDefendus/saskatoon-ng#74]
Maybe we should even have a profile page?

For the short term, just something like "Welcome to Saskatoon, My Name"

**Comment by 2ynn** [comment]
Simply added the username to the header for now, see 3044b6a99992fe5fecc43ee18b43e05ee5e0299b
I think having a welcome message on successful logging could also be nice

**Comment by 2ynn** [comment]
`Hi {{ user }} !` added to index.html
