### ISSUE TITLE
Move mail server configuration to the `.env` file

### ISSUE THREAD

**Issue by tristanlatr** [LesFruitsDefendus/saskatoon-ng#78]
I'm not sure where the mail server configuration is stored right now. 

I think it should be stored in the `.env` file.

**Comment by qusvv** [comment]
I would be interested in documenting the stmp configuration / adding variables in the `.env` (including a `SASKATOON_FROM_EMAIL=info@lesfruitsdefendus.org` variable (see FIXME in `harvest/signals.py`)

https://docs.djangoproject.com/en/3.2/topics/email
I was expecting to find the EMAIL_HOST and EMAIL_PORT  variables in `settings.py`
@tiagovaz do you mind giving a couple details on how you have configured SMTP? 

Currently i need to set `fail_silently=True` in `send_mail()` to add participation_requests. I wouldn't mind skipping the `send_email()` in local development but then maybe this boolean could be added in `.env` too?

**Comment by qusvv** [comment]
See 2a0ad0dafe4918be49bdd31fd792a78b320a3fbd
decided to create a .env template file so settings examples don't spread over too many files

**Comment by tiagovaz** [comment]
I've talked to @qusvv via irc, but just for the record:

```
<tvaz> 10:30:17> # EMAIL #
<tvaz> 10:30:17> EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
[...]
<tvaz> 10:32:58> those are django vars for settings.py as described in https://docs.djangoproject.com/en/3.2/topics/email/
```
