### ISSUE TITLE
Clarify measurement units

### ISSUE THREAD

**Issue by qusvv** [LesFruitsDefendus/saskatoon-ng#81]
- "Height of lowest fruits" in meters or feet in Property Add Form?
- Weight is in lbs in harvestyield Change Form but displays in kg in Admin display_list

**Comment by tiagovaz** [comment]
Yes, please, this needs fix!

**Comment by tristanlatr** [comment]
International System of Units should be used everywhere I think

**Comment by qusvv** [comment]
I'm not sure.. ideally i'd say let's add a `unit` field in HarvestYield but then we will have to deal with conversions before summing the total etc...
If everyone is okay I will push a modification for height in feet (help text in harvest form) and total weight in lbs (in admin inline display) for now.
Note this will create new migrations.

**Comment by tristanlatr** [comment]
I think the core has been putting this values in meters. 
For instance this property https://saskatoon.lesfruitsdefendus.org/harvest/properties/432/update has "2" for the  "Height of lowest fruits" value, so I doubt this is in feets.

**Comment by qusvv** [comment]
Ok I can put meters then, as long as people understand each other that's fine but if noone is incentivized to either enter the value in meters or add the units in the text field you'll get inconsistent data.
