### ISSUE TITLE
Auth.user Create Form doesn't have the 'person' field

### ISSUE THREAD

**Issue by qusvv** [LesFruitsDefendus/saskatoon-ng#84]
Is this on purpose? (e.g. so we can create an authorized user before a related person has been created)

The person field in Auth.User model does not have a `Blank=True` option, meaning a person must necessarily be associated to the authorized user before saving the the Auth.User Change Form.

I see two options:
1. Make the field Blank=True
2. Add 'person' to : AuthUserAdmin(UserAdmin):
```
    add_fieldsets = (
        (
            None, {
                'classes': 'wide',
                'fields': (
                    'email',
                    'password1',
                    'password2',
                    'person',
                    'is_staff',
                    'is_superuser'
                )
            }
        ),
)
```

**Comment by tiagovaz** [comment]
I think Blank=True won't do any harm to the current workflow.

**Comment by tiagovaz** [comment]
Well I'm still not sure actually :\ I think there should be a reason to not have authuser disconnected to a Person. So, my question is: why would we need to have an user disassociated with a Person?

**Comment by qusvv** [comment]
Yes I agree a person should be associated with an auth.user, and this as soon as it is created with the auth.user Create Form (so option 2). It just means the person must be created before the auth.user, I was just wondering if it went against your workflow.

**Comment by tristanlatr** [comment]
>  It just means the person must be created before the auth.user, I was just wondering if it went against your workflow.

The best would be to have only one form to create new users. No matter if they are admins, pick leaders or later tree owners , etc

**Comment by qusvv** [comment]
I have used Auth Groups in the past and find them very useful. This way we could create three groups that each get different privileges: admins, pick-leaders, owners. Switching from one group to another would be very easy, also belonging to multiple groups is possible. Just putting this out there, would need to evaluate the practical implications.

On the same topic I think the Person Dropdown menu in Auth Change Form should be sorted alphabetically

**Comment by qusvv** [comment]
This is what I meant : 66ba2f706a0eb2c489b190bc4359f90ccfca0b78
I pushed to a new authuser branch for now and we can discuss bigger model changes tomorrow

**Comment by qusvv** [comment]
Issues #13 seems related. I would be down to tackle this

**Comment by qusvv** [comment]
closing this, it has been decided to keep it as such until a unified form is created to add a new actor (pickleader/owner/organization). See Issue #12
