### ISSUE TITLE
HarvestForm Update Fails silently

### ISSUE THREAD

**Issue by qusvv** [LesFruitsDefendus/saskatoon-ng#89]
e.g. http://localhost:8000/harvest/update/1/   where 1 is an already existing harvest. 

Send does not save the form:
- `save()` doesn't' get called in `HarvestForm` from `harvest/forms.py`
- `get_success_url()` doesn't get called in `HarvestUpdateView` from `harvest/api.py`

I find this really weird. I don't recall this being the case last week. Creating a new harvest does work though. Could you please try and reproduce this error. Thanks!

**Comment by tristanlatr** [comment]
What is the status of the pick ?
Seems to work on my end.  
What are the exact step you took , UI wise ?

Thanks,

**Comment by qusvv** [comment]
Wow no idea what happened, I had tried on both develop and master branches but now it works again fine. Thanks for double checking!!

**Comment by tristanlatr** [comment]
We need to have those automated tests, it's sketchy !
