### ISSUE TITLE
Unify the layout of all buttons across all windows

### ISSUE THREAD

**Issue by tristanlatr** [LesFruitsDefendus/saskatoon-ng#9]
- The "+" button in the harvest comment box should be replaced by a "Add comment" green button as "Add harvest" button  in property page

- The "+" button in the harvest pickers box should be replaced by a "Add picker" green button as "Add harvest" button in property page

**Comment by tristanlatr** [comment]
This is fixed by the new version

**Comment by tristanlatr** [comment]
Oops I went a little too fast.

Only the "+" icons is still used for comments, pickers requests for participation and fruit distribution.

For accessibility, it would be best that the button says whats it's about.:  "+ comment", "+ picker" and "+ distribution", for instance.

**Comment by 2ynn** [comment]
![screenshot_2021-11-20_11:05:00](https://user-images.githubusercontent.com/41802320/142733026-74303125-3e42-44a1-85c9-c7459b81167b.png)
