### ISSUE TITLE
Avoir un lien franco et un lien anglo pour chaque formulaire / page

### ISSUE THREAD

**Issue by tristanlatr** [LesFruitsDefendus/saskatoon-ng#90]
> Les liens des formulaires de nouveaux propriétaires en français et en anglais aient des liens web différents. Présentement, les liens de formulaire n’ont pas un lien associé et apparaissent en français ou en anglais, selon l’historique de navigation j’ai l’impression… cela serait utile lorsqu’on les partage en ligne sur nos réseaux sociaux d’avoir un lien franco et un lien anglo pour chaque formulaire.

Sur le plan technique, on pourrait accepter un paramètre URL `/property/create_public?lang=en` ou `/property/create_public?lang=fr`, qui forcerait la traduction.

**Comment by 2ynn** [comment]
In addition, I think the public property form should be reformatted:
- split first and last names instead of a single pending_contact_name field
- add a preferred language field

**Comment by 2ynn** [comment]
TODO: fix thank you page

**Comment by yokwejuste** [comment]
What if an API was used for the task? Why try to implement it from scratch when Google Translate tools can obviously b used?

**Comment by 2ynn** [comment]
It's not really from scratch, all strings that need translations should already be marked ( `gettext_lazy()` in py files,  `{% trans "..." %}` in html templates. We just need to update translations.
For reasons that might not be obvious to you we'd rather not use Google.
qynn



Mar 26, 2022, 8:50 PM by ***@***.***:

**Comment by tristanlatr** [comment]
After some discussions with @2ynn, we'll just rely on the language chooser on the top of the pages to so the translations.
