### ISSUE TITLE
Harvest View: Display the status of the harvest with larger text

### ISSUE THREAD

**Issue by tristanlatr** [LesFruitsDefendus/saskatoon-ng#94]
It's currently displayed in the same box as the total amount of fruits picked, and it's not a really big text (see image). 

I think it should have it's own box and the total amount of fruit should only display if the pick has been succeeded. 

![by default 2021-06-05 at 9 03 54 PM](https://user-images.githubusercontent.com/19967168/120909277-8adf5c80-c641-11eb-8309-5fcb4600829a.png)

**Comment by 2ynn** [comment]
![screenshot_2021-07-24_17:13:22](https://user-images.githubusercontent.com/41802320/126881165-e7beed4e-a1ba-4ddb-8445-f6a3c7f9816b.png)
![screenshot_2021-07-24_17:27:14](https://user-images.githubusercontent.com/41802320/126881399-48218592-6b41-42bf-85e2-7f5558623cd5.png)

**Comment by tristanlatr** [comment]
Thanks!
