### ISSUE TITLE
Have welcome page instead of the login form directly

### ISSUE THREAD

**Issue by tristanlatr** [LesFruitsDefendus/saskatoon-ng#95]
<img width="1248" alt="by default 2021-06-05 at 9 11 17 PM" src="https://user-images.githubusercontent.com/19967168/120909384-93846280-c642-11eb-8deb-c3a26179c9da.png">

**Comment by 2ynn** [comment]
logged in pickleader view vs volunteer view on homepage:

![screenshot_2021-06-30_18:03:57](https://user-images.githubusercontent.com/41802320/124037450-979b6a00-d9cd-11eb-8d3d-6e8ce40b3d95.png)

![screenshot_2021-06-30_18:03:33](https://user-images.githubusercontent.com/41802320/124037382-776bab00-d9cd-11eb-883b-c35d91feb2b2.png)

**Comment by 2ynn** [comment]
https://saskatoon-dev.lesfruitsdefendus.org/
