### ISSUE TITLE
showed_up field is not saved based on status answer in RFPManageForm

### ISSUE THREAD

**Issue by qusvv** [LesFruitsDefendus/saskatoon-ng#98]
It looks like the `status` answer (showed up, didn't showed up, cancelled) from `RFPManageForm` (`harvest/forms.py`) is not used in the `save()` method to update the `showed_up` field from the RequestForParticipation instance.

I am currently redesigning the RFP manage form view (see Issue #87).

Would you be interested in adding a column to the pickers data table (on harvest page) indicating if the picker showed up or not (if applicable, i.e. harvest status = successful) ?

**Comment by tristanlatr** [comment]
Better, we could assign pickers score based on their harvesting efficiency, then organise some kind of competition 🤡

Just kidding. 

Honestly I don't know what to think of this... 
Is it useful in the first place to be able to denounce pickers that did not showed up ?

**Comment by qusvv** [comment]
An alternative could be to ask a single question to the pick-leader:
- pending
- accepted
- refused
- cancelled by picker

**Comment by qusvv** [comment]
Simone confirmed that pick leaders never really indicate if picker showed up or not (most show up) and she's okay with the proposition above. working on it

**Comment by qusvv** [comment]
RFPManageForm now has 4 picker request statuses to choose from: `Accepted` / `Refused` / `Pending` / `Cancelled` 

![screenshot_2021-06-08_14:47:01](https://user-images.githubusercontent.com/41802320/121240504-6a451b80-c868-11eb-9c7d-c4df535dc0d6.png)
![screenshot_2021-06-08_14:47:27](https://user-images.githubusercontent.com/41802320/121240506-6addb200-c868-11eb-8562-aae122475782.png)
